### ISSUE TITLE
Received error: SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by crow7m** [gendocu-com/grpc-docs#3]
Hi, Thank you for great plugin, can you please help out with the issue ?
I am receiving Received error: SyntaxError: Unexpected token < in JSON at position 0 when using
`		<GRPCSelfGeneratedAPIReference file='../../../src/proto/description.json'/>
`
where description.json is a valid json file
thank you for your help and support

**Comment by bartek1912** [comment]
Hello,
Could you describe how you the app? So please provide:
- steps to reproduce the issue, like the location of a file, way you run the typescript script (via some external script, our docker image etc.)
- the root page url address (like `localhost:80`)
- the path to a file you mention

At the first glance it seems that the file is not reachable. If that's an issue the fix:
1. Please try running the code from the `example` folder. Clone the repository, then cd into example and run `yarn && yarn start`. You should be able to see an example documentation
2. Uncomment the line: https://github.com/gendocu-com/grpc-docs/blob/master/example/src/App.tsx#L9
3. Rerun the app - you should be able to see a documentation generated from a description file (like your)
4. Replace the description file with your file (replace this file: https://github.com/gendocu-com/grpc-docs/blob/master/example/public/example-descriptors/library-app.json)

I hope it helps ;)

**Comment by crow7m** [comment]
@bartek1912 Thank you for a quick response, after completing all the steps you have specified above, I have managed to run the example, however i would like to ask you why do you have multiple node-modules ? I would like to use genDoc with stand alone component of react, for this purpose I would like to minify the amount of code and dependencies to include only packages needed, react app, and component of genDoc itself, any advice on how to most efficiently to do this and not to break the functionality of the component ? thank  you

**Comment by bartek1912** [comment]
@crow7m There is no way of optimizing the dependency size. We do not have available developers to focus on that optimization
