### ISSUE TITLE
Not all dependencies are coming from well-known registry

### ISSUE THREAD

**Issue by kissmikijr** [gendocu-com/grpc-docs#5]
Hey!

I am in the process to extend a well-known OSS project with a feature to be able to use this library and the `protoc-gen-doc` plugin to render your proto files in [backstage](https://backstage.io/). 

You can check out the PR that would add this functionality [here](https://github.com/backstage/backstage/pull/11746)

However, for that project, it is a requirement that all the dependencies are coming from [https://registry.npmjs.org/](https://registry.npmjs.org/)

### Question
Is it possible to move the GendocuPublicApis to the npm registry?
```
 "GendocuPublicApis": "git+https://git.gendocu.com/gendocu/GendocuPublicApis.git#master"
```

**Comment by kissmikijr** [comment]
@bartek1912 Sorry, it's me again :/ Can you check this one out ? I think it would be really cool to get this package working in backstage!

**Comment by bartek1912** [comment]
Hello @kissmikijr ,
The new version has been released. Let me know when you need any help.

**Comment by depado** [comment]
Hi, sorry to bother you but it seems this change has been reverted. The SSL certificate for `git.gendocu.com` being expired breaks the package installation unfortunately.

**Comment by bartek1912** [comment]
Hello,
Sorry, I manually renewed cert - the issue should be solved ;)

**Comment by depado** [comment]
Thanks :+1:

**Comment by depado** [comment]
Would it be possible to move back to a well-known registry so this issue doesn't happen anymore?

**Comment by bartek1912** [comment]
Hello Depado,
We have a feature in the backlog to auto-publish API packages from GenDocu to npm, but we don't have capacity implement it this year :/

**Comment by depado** [comment]
Alright! Thanks for your reply!
And thank you for this project too! :smile:

**Comment by depado** [comment]
Hi there 👋 
I think this is happening again 😅
